name: Run NTTT

on:
  push:
    branches:
      - actions-test
  pull_request:
    branches:
      - actions-test

jobs:
  translations:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - id: dirs
        run: echo "dirs=$(ls -d */ | jq --raw-input --slurp --compact-output 'split("/\n")[:-1]')" >> $GITHUB_OUTPUT

  nttt:
    needs: translations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        translation: ${{ fromJson(needs.translations.outputs.dirs) }}
        exclude:
          - translation: images
          - translation: solutions
          - translation: resources
          - translation: .github
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install nttt
      - name: Run NTTT
        run: nttt -i ${{ matrix.translation }} -Y on
      - name: Check for changes
        id: git-diff
        run: |
          echo "diff=$(git diff ${{ matrix.translation }})" >> $GITHUB_OUTPUT
          git diff --exit-code ${{ matrix.translation }}
      - name: Update Pull Request
        uses: actions/github-script@v6
        id: git-diff
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### NTTT Diff ðŸ–Œ\`${{ steps.git-diff.outputs.diff }}\`

            *Pushed by: @${{ github.actor }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
